name: CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: |
          pip install pytest pytest-cov
      - name: Run tests with coverage
        run: |
          pytest --cov=your_package_name tests/ --cov-report=xml:coverage.xml --cov-report=html:coverage_html_report
          # Update 'your_package_name' to the package you want to test
